config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'reports#index'
  get 'reports/index'
  get 'reports/year'
  get 'reports/month'
  get 'reports/year_month'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crime.rb
class Crime < ApplicationRecord
  belongs_to :site
  belongs_to :offence
end

app/models/offence.rb
class Offence < ApplicationRecord
  validates :description, uniqueness: true
  has_many :crimes
end

app/models/site.rb
class Site < ApplicationRecord
  validates :neighbourhood, uniqueness: true
  has_many :crimes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @crimes = Crime.all.order(:year, :month, :day, :hour, :minute).paginate(page: params[:page], per_page: 100)
  end

  def year
    @crimes = Crime.select("count(id) as id, offence_id as offence_id, year as year").group(:year, :offence_id).order(:year, :offence_id).paginate(page: params[:page], per_page: 11)
  end

  def month
    @crimes = Crime.select("count(id) as id, offence_id as offence_id, month as month").group(:month, :offence_id).order(:month, :offence_id).paginate(page: params[:page], per_page: 11)
  end

  def year_month
    @crimes = Crime.select("count(id) as id, offence_id as offence_id, month as month, year as year").group(:year, :month, :offence_id).order(:year, :month, :offence_id).paginate(page: params[:page], per_page: 132)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <nav>
    <ul class="nav nav-pills pull-left">
        <li><%= link_to "Home", root_path %></li>
    </ul>
    <ul class="nav nav-pills pull-right">
      <li>&copy;NotungDev 2016</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "VanCrimes", root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- Left Nav-->
      <ul class="nav navbar-nav">
        <li><%= link_to "All", reports_index_path %></li>
        <li><%= link_to "By Year", reports_year_path %></li>
        <li><%= link_to "By Month", reports_month_path %></li>
        <li><%= link_to "By Year/Month", reports_year_month_path %></li>
      </ul>
      <!-- Right Nav-->
      <ul class="nav navbar-nav navbar-right">

      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Vancouver Crimes Report</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="http://code.highcharts.com/highcharts.src.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <%= render 'layouts/footer'%>
      </div>
    </div>
</body>
</html>

app/views/reports/index.html.erb
<h1>All Crimes</h1>
<div class ="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Year</th>
        <th class="text-center">Month</th>
        <th class="text-center">Day</th>
        <th class="text-center">Hour</th>
        <th class="text-center">Minute</th>
        <th class="text-center">Neighbourhood</th>
        <th class="text-center">Offence</th>
      </tr>
    </thead>
    <tbody>
      <% @crimes.each do |crime| %>
        <tr>
          <td class="text-center"><%= crime.year %></td>
          <td class="text-center"><%= crime.month %></td>
          <td class="text-center"><%= crime.day %></td>
          <td class="text-center"><%= crime.hour %></td>
          <td class="text-center"><%= crime.minute %></td>
          <td class="text-center"><%= crime.site.neighbourhood || "" %></td>
          <td class="text-center"><%= crime.offence.description %></td>          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @crimes, renderer: BootstrapPagination::Rails %>

app/views/reports/month.html.erb
<h1>Crimes By Month</h1>

<div id="container" style="width:100%; height:800px;"></div>

<div class ="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Offence</th>
        <th class="text-center">Occurences</th>
        <th class="text-center">Month</th>
      </tr>
    </thead>
    <tbody>
      <% @crimes.each do |crime| %>
        <tr>
          <td class="text-center"><%= crime.offence.description %></td>
          <td class="text-center"><%= crime.id %></td>
          <td class="text-center"><%= crime.month %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @crimes, renderer: BootstrapPagination::Rails %>

<script>
$(function () {
  $('#container').highcharts({
      chart: { type: 'line' },
      title: { text: '<%= raw "Crime Occurences in #{@crimes.first.month}" %>' },
      xAxis: { categories: <%= raw @crimes.map{|crime| crime.offence.description}.to_json %> },
      yAxis: { title: { text: 'Occurences' } },
      series: [{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        },{
          name: <%= raw @crimes.first.month %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
        }
      ]
  });
});
</script>

app/views/reports/year.html.erb
<h1>Crimes by Year</h1>

<div id="container" style="width:100%; height:400px;"></div>

<div class ="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Offence</th>
        <th class="text-center">Occurences</th>
        <th class="text-center">Year</th>
      </tr>
    </thead>
    <tbody>
      <% @crimes.each do |crime| %>
        <tr>
          <td class="text-center"><%= crime.offence.description %></td>
          <td class="text-center"><%= crime.id %></td>
          <td class="text-center"><%= crime.year %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @crimes, renderer: BootstrapPagination::Rails %>

<script>
$(function () {
  $('#container').highcharts({
      chart: { type: 'column' },
      title: { text: '<%= raw "Crime Occurences in #{@crimes.first.year}" %>' },
      xAxis: { categories: <%= raw @crimes.map{|crime| crime.offence.description}.to_json %> },
      yAxis: { title: { text: 'Occurences' } },
      series: [{
          name: <%= raw @crimes.first.year %>,
          data: <%= raw @crimes.map{|crime| crime.id}.to_json %>
      }]
  });
});
</script>

app/views/reports/year_month.html.erb
<h1>Crimes by Year/Month</h1>
<div class ="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Offence</th>
        <th class="text-center">Occurences</th>
        <th class="text-center">Year</th>
        <th class="text-center">Month</th>
      </tr>
    </thead>
    <tbody>
      <% @crimes.each do |crime| %>
        <tr>
          <td class="text-center"><%= crime.offence.description %></td>
          <td class="text-center"><%= crime.id %></td>
          <td class="text-center"><%= crime.year %></td>
          <td class="text-center"><%= crime.month %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @crimes, renderer: BootstrapPagination::Rails %>